### ISSUE TITLE
修改有效，但是无法缓存

### ISSUE THREAD

**Issue by yizhishang** [zongwei007/drone-maven-setting#1]
每次都是重新拉取依赖包

**Comment by zongwei007** [comment]
@yizhishang 能否贴出 pipline 配置？

**Comment by yizhishang** [comment]
我用的drone版本是最新的
![image](https://user-images.githubusercontent.com/12756407/62747416-e6148800-ba86-11e9-8dac-b397d917e5a9.png)
settings.xml 的确是按照预期的生成出来的了，镜像还是从默认的仓库下面拉出来的，
另外maven镜像有个默认的docker-settings.xml没搞懂这个是干嘛的

**Comment by yizhishang** [comment]
$${env.USER_NAME} 这种变量在生成的settings.xml没有体现出来

**Comment by yizhishang** [comment]
已经缓存了，但是还是有个问题，$${env.USER_NAME} 这个获取不到值

**Comment by yizhishang** [comment]
![image](https://user-images.githubusercontent.com/12756407/62761852-4c66ce00-baba-11e9-80fa-3b164bd8565a.png)

**Comment by yizhishang** [comment]
xiami下面是我的配置
![image](https://user-images.githubusercontent.com/12756407/62761877-63a5bb80-baba-11e9-96ff-6cba96c26c73.png)

**Comment by yizhishang** [comment]
${env.USER_NAME} 没有拿到值

**Comment by zongwei007** [comment]
插件的 settings.xml 转换没有问题。这里的写法就是在执行 mvn 命令时从环境变量中读取 USER_NAME 作为值。如果在执行 mvn 命令时读不到 USER_NAME，试试检查 Drone 项目的 Secrets 设置，并尝试在 commands 中打印一下环境变量。

**Comment by yizhishang** [comment]
我试过在command打印，什么都没有

**Comment by zongwei007** [comment]
@yizhishang 想起来了，Drone 会将控制台中关于 Secrets 的内容隐藏，所以要用特别的方法输出。比如：

```yml
  - name: output
    image: node
    environment:
      USER_NAME:
        from_secret: ssh_username
    commands:
      - node -e "console.log(process.env.USER_NAME)"
```

这样能输出一串 `*`
